/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Actions
         * @description Return action id to string mapping for the UI.
         */
        get: operations["get_actions_api_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Simulate
         * @description Simulate a full Sheepshead game and return detailed analysis trace.
         */
        post: operations["analyze_simulate_api_analyze_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_api_players__player_id__patch"];
        trace?: never;
    };
    "/api/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tables */
        get: operations["list_tables_api_tables_get"];
        put?: never;
        /** Create Table */
        post: operations["create_table_api_tables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Action */
        post: operations["post_action_api_tables__table_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Close Table */
        post: operations["api_close_table_api_tables__table_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/fill_ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fill Ai */
        post: operations["fill_ai_api_tables__table_id__fill_ai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Table */
        post: operations["join_table_api_tables__table_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/redeal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeal */
        post: operations["redeal_api_tables__table_id__redeal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Table Rules */
        patch: operations["update_table_rules_api_tables__table_id__rules_patch"];
        trace?: never;
    };
    "/api/tables/{table_id}/seat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose Seat */
        post: operations["choose_seat_api_tables__table_id__seat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Game */
        post: operations["start_game_api_tables__table_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe for uptime checks and container healthchecks.
         *
         *     Always returns 200 while the process is serving; ``db`` reports
         *     best-effort connectivity so a degraded database shows up in monitoring
         *     without taking the probe (and thus the container) down with it.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /** Action Id */
            action_id: number;
            /** Client Id */
            client_id: string;
        };
        /** ActionsLookupResponse */
        ActionsLookupResponse: {
            /** Action Lookup */
            action_lookup: {
                [key: string]: string;
            };
        };
        /** AnalyzeActionDetail */
        AnalyzeActionDetail: {
            /** Action */
            action: string;
            /** Actionid */
            actionId: number;
            /** Discountedreturn */
            discountedReturn?: number | null;
            /** Expectedfinalreturn */
            expectedFinalReturn?: number | null;
            /** Memorycosinedistance */
            memoryCosineDistance?: number | null;
            /** Memorynorm */
            memoryNorm?: number | null;
            observation: components["schemas"]["AnalyzeObservation"];
            /** Oraclevalue */
            oracleValue?: number | null;
            /** Phase */
            phase: string;
            /** Pointactuals */
            pointActuals?: components["schemas"]["AnalyzePointEstimate"][] | null;
            /** Pointestimates */
            pointEstimates?: components["schemas"]["AnalyzePointEstimate"][] | null;
            /** Probabilities */
            probabilities: components["schemas"]["AnalyzeProbability"][];
            /** Seat */
            seat: number;
            /** Seatname */
            seatName: string;
            /** Secretpartnerprob */
            secretPartnerProb?: number | null;
            /** Stepindex */
            stepIndex: number;
            /** Stepreward */
            stepReward?: number | null;
            /** Steprewardbase */
            stepRewardBase?: number | null;
            /** Steprewardheadshaping */
            stepRewardHeadShaping?: number | null;
            /** Steprewardterminal */
            stepRewardTerminal?: number | null;
            /** Trumpseenmask */
            trumpSeenMask?: components["schemas"]["AnalyzeTrumpSeenMaskEntry"][] | null;
            /** Unseentrumphigherthanhandactual */
            unseenTrumpHigherThanHandActual?: boolean | null;
            /** Unseentrumphigherthanhandprob */
            unseenTrumpHigherThanHandProb?: number | null;
            /** Validactionids */
            validActionIds: number[];
            /** Valueestimate */
            valueEstimate: number;
            /** View */
            view: {
                [key: string]: unknown;
            };
            /** Winprob */
            winProb?: number | null;
        };
        /** AnalyzeGameSummary */
        AnalyzeGameSummary: {
            /** Blind */
            blind: string[];
            /** Bury */
            bury: string[];
            /** Defenderpoints */
            defenderPoints: number;
            /** Hands */
            hands: {
                [key: string]: string[];
            };
            /** Partner */
            partner?: string | null;
            /** Picker */
            picker?: string | null;
            /** Pickerpoints */
            pickerPoints: number;
            /** Scores */
            scores: number[];
        };
        /**
         * AnalyzeObservation
         * @description The observation the model actually received (Player.get_state_dict),
         *     decoded from card ids to card codes. Blind/bury are empty unless the
         *     actor is the picker — this mirrors exactly what the actor sees, unlike
         *     the omniscient `view`.
         */
        AnalyzeObservation: {
            /** Alonecalled */
            aloneCalled: boolean;
            /** Blind */
            blind: string[];
            /** Bury */
            bury: string[];
            /** Calledcard */
            calledCard?: string | null;
            /** Calledunder */
            calledUnder: boolean;
            /** Currenttrick */
            currentTrick: number;
            /** Hand */
            hand: string[];
            /** Isleaster */
            isLeaster: boolean;
            /** Leaderrel */
            leaderRel: number;
            /** Partnermode */
            partnerMode: number;
            /** Partnerrel */
            partnerRel: number;
            /** Pickerposition */
            pickerPosition: number;
            /** Pickerrel */
            pickerRel: number;
            /** Playstarted */
            playStarted: boolean;
            /** Trick */
            trick: components["schemas"]["AnalyzeObservationTrickSlot"][];
        };
        /** AnalyzeObservationTrickSlot */
        AnalyzeObservationTrickSlot: {
            /** Card */
            card?: string | null;
            /** Ispartnerknown */
            isPartnerKnown: boolean;
            /** Ispicker */
            isPicker: boolean;
            /** Relativeposition */
            relativePosition: number;
            /** Seat */
            seat: number;
            /** Seatname */
            seatName: string;
        };
        /** AnalyzePointEstimate */
        AnalyzePointEstimate: {
            /** Points */
            points: number;
            /** Relativeposition */
            relativePosition: number;
            /** Seat */
            seat: number;
            /** Seatname */
            seatName: string;
        };
        /** AnalyzeProbability */
        AnalyzeProbability: {
            /** Action */
            action: string;
            /** Actionid */
            actionId: number;
            /** Logit */
            logit: number;
            /** Prob */
            prob: number;
        };
        /** AnalyzeSimulateRequest */
        AnalyzeSimulateRequest: {
            /**
             * Deterministic
             * @default false
             */
            deterministic: boolean;
            /**
             * Maxsteps
             * @default 200
             */
            maxSteps: number;
            /**
             * Partnermode
             * @default 1
             */
            partnerMode: number;
            /** Seed */
            seed?: number | null;
        };
        /** AnalyzeSimulateResponse */
        AnalyzeSimulateResponse: {
            /** Final */
            final?: {
                [key: string]: unknown;
            } | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            summary?: components["schemas"]["AnalyzeGameSummary"] | null;
            /** Trace */
            trace: components["schemas"]["AnalyzeActionDetail"][];
        };
        /** AnalyzeTrumpSeenMaskEntry */
        AnalyzeTrumpSeenMaskEntry: {
            /** Actualseen */
            actualSeen: boolean;
            /** Card */
            card: string;
            /** Probabilityseen */
            probabilitySeen: number;
        };
        /** CloseTableRequest */
        CloseTableRequest: {
            /** Client Id */
            client_id: string;
        };
        /** CreateTableRequest */
        CreateTableRequest: {
            /**
             * Fillwithai
             * @default true
             */
            fillWithAI: boolean;
            /** Name */
            name: string;
            rules?: components["schemas"]["RulesInput"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Db */
            db: boolean;
            /** Model */
            model: string;
            /** Status */
            status: string;
        };
        /** JoinTableRequest */
        JoinTableRequest: {
            /** Display Name */
            display_name: string;
        };
        /** JoinTableResponse */
        JoinTableResponse: {
            /** Client Id */
            client_id: string;
            /** Is Host */
            is_host: boolean;
            /** Player Id */
            player_id: string;
            /** Session Token */
            session_token: string | null;
            table: components["schemas"]["TablePublic"];
        };
        /** OkResponse */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** PlayerPublic */
        PlayerPublic: {
            /** Name */
            name: string | null;
            /** Player Id */
            player_id: string;
        };
        /** RedealRequest */
        RedealRequest: {
            /** Client Id */
            client_id?: string | null;
        };
        /**
         * RulesInput
         * @description Full rules specification; unknown keys rejected.
         */
        RulesInput: {
            /**
             * Doubleonthebump
             * @default true
             */
            doubleOnTheBump: boolean;
            /**
             * Partnermode
             * @default 1
             * @enum {integer}
             */
            partnerMode: 0 | 1;
        };
        /**
         * RulesUpdate
         * @description Partial rules patch; only provided keys are merged.
         */
        RulesUpdate: {
            /** Doubleonthebump */
            doubleOnTheBump?: boolean | null;
            /** Partnermode */
            partnerMode?: (0 | 1) | null;
        };
        /** RulesUpdateResponse */
        RulesUpdateResponse: {
            rules: components["schemas"]["RulesInput"];
            /** Status */
            status: string;
        };
        /** SeatRequest */
        SeatRequest: {
            /** Client Id */
            client_id: string;
            /** Seat */
            seat: number;
        };
        /** StartGameRequest */
        StartGameRequest: {
            /** Client Id */
            client_id: string;
            /** Seed */
            seed?: number | null;
        };
        /** TablePublic */
        TablePublic: {
            /** Fillwithai */
            fillWithAI: boolean;
            /** Host */
            host: string | null;
            /** Id */
            id: string;
            /** Initialnames */
            initialNames: {
                [key: string]: string;
            };
            /** Initialseatorder */
            initialSeatOrder: string[];
            /** Name */
            name: string;
            /** Resultshistory */
            resultsHistory: {
                [key: string]: unknown;
            }[];
            rules: components["schemas"]["RulesInput"];
            /** Runningbyseat */
            runningBySeat: {
                [key: string]: number;
            };
            /** Seatisai */
            seatIsAI: {
                [key: string]: boolean;
            };
            /** Seatoccupants */
            seatOccupants: {
                [key: string]: string | null;
            };
            /** Seats */
            seats: {
                [key: string]: string | null;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "playing" | "finished";
        };
        /** UpdatePlayerRequest */
        UpdatePlayerRequest: {
            /** Name */
            name?: string | null;
        };
        /** UpdateTableRulesRequest */
        UpdateTableRulesRequest: {
            /** Client Id */
            client_id: string;
            rules: components["schemas"]["RulesUpdate"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_actions_api_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionsLookupResponse"];
                };
            };
        };
    };
    analyze_simulate_api_analyze_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeSimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_api_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlayerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tables_api_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePublic"][];
                };
            };
        };
    };
    create_table_api_tables_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_action_api_tables__table_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_close_table_api_tables__table_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseTableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fill_ai_api_tables__table_id__fill_ai_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RedealRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_table_api_tables__table_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinTableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeal_api_tables__table_id__redeal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RedealRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_table_rules_api_tables__table_id__rules_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTableRulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_seat_api_tables__table_id__seat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_game_api_tables__table_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
