-- Generated by scripts/gen_card_seed.py — do not edit by hand.
-- Re-run the script after changing DECK / SUIT_NAMES in sheepshead.py.

BEGIN;

-- Reference rows are static. ON CONFLICT DO NOTHING makes this safe to run
-- multiple times (afterAllMigrations fires after every migrate, not just reset).
INSERT INTO suit (suit_id, code, name) VALUES
    (1, 'C', 'Clubs'),
    (2, 'S', 'Spades'),
    (3, 'H', 'Hearts'),
    (4, 'D', 'Diamonds')
ON CONFLICT (suit_id) DO NOTHING;

INSERT INTO card (card_id, suit_id, code, name) VALUES
    (1, 1, 'QC', 'Queen of Clubs'),
    (2, 2, 'QS', 'Queen of Spades'),
    (3, 3, 'QH', 'Queen of Hearts'),
    (4, 4, 'QD', 'Queen of Diamonds'),
    (5, 1, 'JC', 'Jack of Clubs'),
    (6, 2, 'JS', 'Jack of Spades'),
    (7, 3, 'JH', 'Jack of Hearts'),
    (8, 4, 'JD', 'Jack of Diamonds'),
    (9, 4, 'AD', 'Ace of Diamonds'),
    (10, 4, '10D', 'Ten of Diamonds'),
    (11, 4, 'KD', 'King of Diamonds'),
    (12, 4, '9D', 'Nine of Diamonds'),
    (13, 4, '8D', 'Eight of Diamonds'),
    (14, 4, '7D', 'Seven of Diamonds'),
    (15, 1, 'AC', 'Ace of Clubs'),
    (16, 1, '10C', 'Ten of Clubs'),
    (17, 1, 'KC', 'King of Clubs'),
    (18, 1, '9C', 'Nine of Clubs'),
    (19, 1, '8C', 'Eight of Clubs'),
    (20, 1, '7C', 'Seven of Clubs'),
    (21, 2, 'AS', 'Ace of Spades'),
    (22, 2, '10S', 'Ten of Spades'),
    (23, 2, 'KS', 'King of Spades'),
    (24, 2, '9S', 'Nine of Spades'),
    (25, 2, '8S', 'Eight of Spades'),
    (26, 2, '7S', 'Seven of Spades'),
    (27, 3, 'AH', 'Ace of Hearts'),
    (28, 3, '10H', 'Ten of Hearts'),
    (29, 3, 'KH', 'King of Hearts'),
    (30, 3, '9H', 'Nine of Hearts'),
    (31, 3, '8H', 'Eight of Hearts'),
    (32, 3, '7H', 'Seven of Hearts')
ON CONFLICT (card_id) DO NOTHING;

COMMIT;
