#!/usr/bin/env python3
"""Generate db/fixtures/afterReset.sql from sheepshead.py constants.

Run from the repo root after any change to DECK / SUIT_NAMES /
CARD_FULL_NAMES so the seed stays in sync with the game engine:

    uv run python scripts/gen_card_seed.py

The output is committed.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from sheepshead import CARD_FULL_NAMES, DECK, DECK_IDS, SUIT_NAMES  # noqa: E402

OUT_PATH = REPO_ROOT / "db" / "fixtures" / "afterReset.sql"

# Deterministic suit_id ordering as documented in WebServerUpdatePlan §3.4.
SUIT_ORDER = [("C", 1), ("S", 2), ("H", 3), ("D", 4)]


def render() -> str:
    lines: list[str] = []
    lines.append("-- Generated by scripts/gen_card_seed.py — do not edit by hand.")
    lines.append(
        "-- Re-run the script after changing DECK / SUIT_NAMES in sheepshead.py."
    )
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("-- Reference rows are static; clear and reinsert on every reset.")
    lines.append("DELETE FROM cardset_card;")
    lines.append("DELETE FROM card;")
    lines.append("DELETE FROM suit;")
    lines.append("")
    lines.append("INSERT INTO suit (suit_id, code, name) VALUES")
    suit_values = []
    for code, suit_id in SUIT_ORDER:
        name = SUIT_NAMES[code].replace("'", "''")
        suit_values.append(f"    ({suit_id}, '{code}', '{name}')")
    lines.append(",\n".join(suit_values) + ";")
    lines.append("")
    lines.append("INSERT INTO card (card_id, suit_id, code, name) VALUES")
    suit_id_by_code = {c: i for c, i in SUIT_ORDER}
    card_values = []
    for code in DECK:
        card_id = DECK_IDS[code]
        suit_letter = code[-1]
        suit_id = suit_id_by_code[suit_letter]
        full_name = CARD_FULL_NAMES[code].replace("'", "''")
        card_values.append(f"    ({card_id}, {suit_id}, '{code}', '{full_name}')")
    lines.append(",\n".join(card_values) + ";")
    lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render())
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
